# Generated by Django 2.2 on 2019-04-25 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(db_column='role', max_length=50)),
                ('From', models.CharField(db_column='from', max_length=50)),
                ('to', models.CharField(db_column='to', max_length=50)),
            ],
            options={
                'db_table': 'leaveroute',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('emp_ID', models.EmailField(db_column='email_id', max_length=100)),
                ('leave_ID', models.CharField(db_column='leave_id', max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='status', max_length=50)),
                ('date', models.DateField()),
                ('text', models.TextField(max_length=300)),
                ('concern_auth', models.ForeignKey(db_column='concern_auth', null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.Employee')),
            ],
            options={
                'db_table': 'leave',
            },
        ),
    ]
