# Generated by Django 2.2 on 2019-04-25 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTable',
            fields=[
                ('emailID', models.EmailField(db_column='email_id', max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='password', max_length=256)),
                ('role', models.CharField(db_column='role', max_length=50)),
            ],
            options={
                'db_table': 'authtable',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_ID', models.IntegerField(db_column='dept_id', primary_key=True, serialize=False)),
                ('dept_name', models.CharField(db_column='dept_name', max_length=40)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=30)),
                ('last_name', models.CharField(db_column='last_name', max_length=30)),
                ('date_of_birth', models.DateField(db_column='date_of_birth')),
                ('gender', models.CharField(db_column='gender', max_length=10)),
                ('address', models.TextField(db_column='address')),
                ('PAN', models.CharField(db_column='pan', max_length=50, null=True)),
                ('date_of_join', models.DateField(db_column='date_of_join')),
                ('current_role', models.CharField(choices=[('STAFF', 'STAFF'), ('FACULTY', 'FACULTY'), ('CCFS', 'CCFS'), ('DIRECTOR', 'DIRECTOR'), ('REGISTRAR', 'REGISTRAR'), ('ASSIST_REGISTRAR', 'ASSIST_REGISTRAR'), ('HOD', 'HOD'), ('DFA', 'DEAN FACULTY AFFAIR'), ('ADFA', 'ASSOCIATE DEAN FACULTY AFFAIR'), ('DEPSEC', 'DEPARTMENT SECRETARY')], db_column='current_role', max_length=20)),
                ('leave_available', models.IntegerField(db_column='leave_available')),
                ('borrow_available', models.IntegerField(db_column='borrow_available')),
                ('grade_of_employment', models.CharField(db_column='grade_of_employment', default='A', max_length=20)),
                ('past_experience', models.IntegerField(db_column='past_experience', default=0)),
                ('contact', models.CharField(db_column='contact', max_length=12, null=True)),
                ('emp_ID', models.OneToOneField(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.AuthTable')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Ccfs',
            fields=[
                ('ccfs_id', models.OneToOneField(db_column='ccfs_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.Employee')),
                ('dept_ID', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.Department')),
            ],
            options={
                'db_table': 'ccfs',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.OneToOneField(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.Employee')),
                ('dept_ID', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.Department')),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.OneToOneField(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.Employee')),
                ('dept_ID', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.Department')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('regID', models.AutoField(db_column='reg_id', primary_key=True, serialize=False)),
                ('regEmail', models.EmailField(db_column='reg_email', max_length=100)),
                ('start_date', models.DateField(db_column='start_date')),
                ('end_date', models.DateField(db_column='end_date', null=True)),
                ('staff_id', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.Staff')),
            ],
            options={
                'db_table': 'registrar',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.AutoField(db_column='post_id', primary_key=True, serialize=False)),
                ('postEmail', models.EmailField(db_column='post_email', max_length=100)),
                ('start_date', models.DateField(db_column='start_date')),
                ('end_date', models.DateField(db_column='end_date', null=True)),
                ('name', models.CharField(choices=[('DFA', 'DEAN FACULTY AFFAIR'), ('ADFA', 'ASSOCIATE DEAN FACULTY AFFAIR'), ('DEPTSEC', 'DEPARTMENT SECRETARY')], db_column='post_name', max_length=20)),
                ('ccfs', models.ForeignKey(db_column='ccfs_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.Ccfs')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('hodID', models.AutoField(db_column='hod_id', primary_key=True, serialize=False)),
                ('hodEmail', models.EmailField(db_column='hod_email', max_length=100)),
                ('start_date', models.DateField(db_column='start_date')),
                ('end_date', models.DateField(db_column='end_date', null=True)),
                ('faculty_ID', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.Faculty')),
            ],
            options={
                'db_table': 'hod',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('dirID', models.AutoField(db_column='dir_id', primary_key=True, serialize=False)),
                ('dirEmail', models.EmailField(db_column='dir_email', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('faculty_ID', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.Faculty')),
            ],
            options={
                'db_table': 'director',
            },
        ),
        migrations.CreateModel(
            name='AssistRegistrar',
            fields=[
                ('assRegID', models.AutoField(db_column='ass_reg_id', primary_key=True, serialize=False)),
                ('assRegEmail', models.EmailField(db_column='ass_reg_email', max_length=100)),
                ('start_date', models.DateField(db_column='start_date')),
                ('end_date', models.DateField(db_column='end_date', null=True)),
                ('staff_id', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.Staff')),
            ],
            options={
                'db_table': 'assist_registrar',
            },
        ),
    ]
