# Generated by Django 2.2 on 2019-04-25 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(db_column='date')),
                ('year', models.IntegerField(db_column='year')),
                ('bonus', models.DecimalField(db_column='bonus', decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'calender',
            },
        ),
        migrations.CreateModel(
            name='Cfti',
            fields=[
                ('cftiID', models.AutoField(db_column='cfti_id', primary_key=True, serialize=False)),
                ('experience', models.IntegerField(db_column='experience')),
                ('grade', models.CharField(db_column='grade', max_length=20)),
                ('baseSalary', models.DecimalField(db_column='salary', decimal_places=2, max_digits=30)),
                ('lastUpdated', models.DateTimeField(db_column='last_updated')),
            ],
            options={
                'db_table': 'cfti',
            },
        ),
        migrations.CreateModel(
            name='paperTrailPayslip',
            fields=[
                ('paperTrailID', models.AutoField(db_column='paperTrailID', primary_key=True, serialize=False)),
                ('payslip_id', models.IntegerField(db_column='payslip_id')),
                ('date', models.DateField(db_column='date')),
                ('comment', models.TextField(db_column='comment', null=True)),
                ('role', models.CharField(db_column='role', max_length=20)),
                ('empIDGen', models.IntegerField(db_column='empIDGen')),
                ('status', models.CharField(db_column='status', max_length=20)),
            ],
            options={
                'db_table': 'paperTrailPayslip',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('payslip_id', models.CharField(db_column='payslip_id', max_length=50)),
                ('payslip_ownerName', models.CharField(max_length=50, null=True)),
                ('month', models.IntegerField(db_column='month', null=True)),
                ('year', models.IntegerField(db_column='year', null=True)),
                ('experience', models.IntegerField(db_column='experience', null=True)),
                ('grade_of_employment', models.CharField(db_column='grade_of_employment', default='A', max_length=20)),
                ('base_salary', models.DecimalField(db_column='salary', decimal_places=2, max_digits=30, null=True)),
                ('bonus_received', models.DecimalField(db_column='bonus', decimal_places=2, max_digits=30, null=True)),
                ('total_salary', models.DecimalField(db_column='total_salary', decimal_places=2, max_digits=30, null=True)),
                ('date_of_generation', models.DateField(db_column='date_of_generation', null=True)),
                ('approvedByAccountSection', models.BooleanField(db_column='approvedByAccountSection', default=None, null=True)),
                ('approvedByAssistRegistrar', models.BooleanField(db_column='approvedByAssistRegistrar', default=None, null=True)),
                ('slip_emp', models.ForeignKey(db_column='slip_emp', null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.Employee')),
                ('slip_gen', models.ForeignKey(db_column='slip_gen', null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.Ccfs')),
                ('slip_gen_ar', models.ForeignKey(db_column='slip_gen_ar', null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.AssistRegistrar')),
            ],
            options={
                'db_table': 'payslip',
            },
        ),
    ]
